### ISSUE TITLE
Lookup type: Multiselection don't working

### ISSUE THREAD

**Issue by stefanobasta** [cosmocode/dokuwiki-plugin-struct#222]
There are two possibilities to use multi-selection for the lookup type:
In the lookup schema and in the page schema.
Multi-selection for lookup schema OFF, page schema OFF: dropdown field works fine without multi-selection
Lookup schema ON, page schema OFF: Field keyword.Keyword is a multi field - not allowed for lookup
Lookup schema OFF, page schema ON: show only the separation comma without text after the choice
Lookup schema ON, page schema ON: Field keyword.Keyword is a multi field - not allowed for lookup
Detail: Lockup type=>texte, template=>bootstrap

**Comment by micgro42** [comment]
> Lookup schema OFF, page schema ON: show only the separation comma without text after the choice

This works for me as expected. But there might be some unrelated styling problems, see #201 .

> Lookup schema ON, page schema OFF: Field keyword.Keyword is a multi field - not allowed for lookup
> Lookup schema ON, page schema ON: Field keyword.Keyword is a multi field - not allowed for lookup

This behavior is indeed buggy and should be fixed.

**Comment by splitbrain** [comment]
Please make sure you're using the latest version of the struct and sqlite plugins. This has already been fixed in 7f4c224aa66504da5b6b72a5c021862932b028b3 and d329f04c26fb0f51f0764a43c99a6f9f140a9d7d

**Comment by stefanobasta** [comment]
sorry, the error persist.
structured data version: 2016-03-11
squite version: 2016-11-15
Do you need more details ?

**Comment by splitbrain** [comment]
2016-03-11 is several months old!?

**Comment by stefanobasta** [comment]
sorry structured data isn't the right plugin: struct plugin: 2016-11-17

**Comment by stefanobasta** [comment]
OK, it works well for new created lookup types ;-) Former created lookup types?? 
Thank you
